Merge branch 'main' of https://github.com/Oluwasetemi/altschool-opensource-names
Oluwasetemi/altschool-opensource-names pull request #134
Opened 2022-08-08 10:25 UTC by kkins25

2022-08-08 10:37 UTC, oseunabiola requested changes
Kindly remove all lines that are not for names.

2022-08-08 10:37 UTC, oseunabiola commented on names.txt
> +<<<<<<< HEAD
Kindly remove all lines that are not for names.

2022-08-15 12:02 UTC, tobisupreme commented
Hi Kingsley! 😁

We are here for you for the next 6 hours before we close this PR so you can initiate a fresh one which will be easier to merge.

Please refer to the updated README 🙏

2022-08-15 12:07 UTC, Oluwasetemi commented
Please I am sorry for all the trouble we have caused you but count it all joy. Your PR is about to be merged and you will be able to see your name on this [url](https://altschool-opensource-names.oluwasetemi.dev/). 

To enable me to do this, **READ the README again carefully**, update your code with the latest and push the update. I am here for you for the next **6 hours** before I close the PR so you can initiate a fresh PR which will be easier to merge.

2022-08-15 14:38 UTC, closed without merging